// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentState } from "./CollabAgentState";

export type CollabAgentStatusEntry = { threadId: string, agentNickname: string | null, agentRole: string | null, status: CollabAgentState, };
